#include <iostream>
#include <string>
#include <cmath>

using namespace std;

    // 3. Запросить у пользователя число и вывести его модуль 
    // (|7| = 7, |-7| = 7).


    int main()
        {
            int X;
            int Y;
            cout << "X";
            cin >> X;
            cout << "Y";
            cin >> Y;
            if (x == 0 && y == 0) {
                cout << "We're standing still, sir!";
            } else if (x == )
            
        }